### PR TITLE
Error handling when range has formulas which return #NA. 

### PR DESCRIPTION
**Pull request by shirisha95**
While accessing ws.range("A2:A100") if formulas can't be evaluated - all of them returns NA. we get an exception as we try and access -> c.value[0] in line 109 which results in this error

### CODE REVIEW

**Comment by fzumstein** [comment]
Can you please attach a sample workbook to reproduce (or write a test)?

**Comment by fzumstein** [comment]
@shirisha95 did you see my comment?

**Comment by shirisha95** [comment]
Code for testing:
`import xlwings as xw
wb = xw.Book('test8.xlsx')
ws = wb.sheets['Summary']
print(ws.range("B2:B4").value)
wb.save()`

[test8.xlsx](https://github.com/ZoomerAnalytics/xlwings/files/2854619/test8.xlsx)

**Comment by fzumstein** [comment]
I get the following output of your test function with the test code:
```
[-2146826246, -2146826246, -2146826246]
```

Which is logged as this bug (which should admittedly get fixed): https://github.com/ZoomerAnalytics/xlwings/issues/61

**Comment by fzumstein** [comment]
I get the following output of your test function with the test code:
```
[-2146826246, -2146826246, -2146826246]
```

Which is logged as this bug (which should admittedly get fixed): https://github.com/ZoomerAnalytics/xlwings/issues/61

**Comment by fzumstein** [comment]
replaced by #1060

**Pull request closed without merging**
