### PR TITLE
fix iterator issue #272 and add test

### PR DESCRIPTION
**Pull request by sdementen**

### CODE REVIEW

**Comment by fzumstein** [comment]
Fails on Python 3: `AttributeError: module 'itertools' has no attribute 'imap'`

**Comment by sdementen** [comment]
I have done the fix for python 3, tests run OK on python 2.7

**Comment by fzumstein** [comment]
that's not enough to make it work across versions, but I've fixed it now: 4b72041c0150315f30bd7acd81feadb4e83a3a08

**Comment by sdementen** [comment]
indeed, I'll try to setup of py3 test environment to avoid such issues in the future

**Pull request merged**
