### PR TITLE
implement Range properties: column_width, row_height, width, height

### PR DESCRIPTION
**Pull request by kgrudzin**
Implements #81. The Range object now has the properties column_width, row_height, width, and height.

Excel behaves a little strangely when getting the column_width of a range outside the used range of the worksheet when the columns have different widths. It returns with width of the first column instead of None, hence the note in the documentation. Similar result for row_height. This is consistent with how VBA in Excel behaves however.

Note: This is untested on Mac

### CODE REVIEW

**Comment by fzumstein** [comment]
Thanks for this great PR!

**Comment by fzumstein** [comment]
@kgrudzin hey I saw your left-top branch - any chance for a PR sometimes soon?

**Comment by kgrudzin** [comment]
Yes, I'll clean it up and make a PR soon

**Comment by fzumstein** [comment]
awesome thanks!

**Pull request merged**
