### PR TITLE
fixed Workbook.active_sheet by making it a property

### PR DESCRIPTION
**Pull request by gdementen**
```python
>>> import xlwings as xw
>>> wb = xw.Workbook.active()
<Sheet 'Sheet2' of Workbook 'Book12'>
>>> # this is bad !
>>> wb.active_sheet
<Sheet 'Sheet1' of Workbook 'Book12'>
```

### CODE REVIEW

**Comment by fzumstein** [comment]
Hey thanks for all the contributions - just quick general remark: could you submit future PRs against the develop branch?

**Comment by gdementen** [comment]
sure... when I get back to this. It will probably not be for a while though.

**Comment by fzumstein** [comment]
manually merged into develop

**Comment by gdementen** [comment]
Thanks!

**Pull request closed without merging**
