### PR TITLE
get_comment & set_comment

### PR DESCRIPTION
**Pull request by geek-ragazza**
get_comment & set_comment

### CODE REVIEW

**Comment by fzumstein** [comment]
There's already an open PR #238  for that...

**Comment by geek-ragazza** [comment]
Thank you ! I suggest that add decode ('utf-8') before value write into comment.
Because if you use Chinese without decode utf-8.
Chinese will become garbled.
value=(value).decode('utf-8')
xl_range.Comment.Text(value)

**Comment by fzumstein** [comment]
OK, I ll look into that. But for standard Cell values as in `Range('A1').value = u'some Chinese'` it works correctly, right?

**Comment by geek-ragazza** [comment]
Yes, it works correctly :+1:  Thank you

**Pull request closed without merging**
