### PR TITLE
resize function + improve doc + fix tests (fix issue #262)

### PR DESCRIPTION
**Pull request by sdementen**
Felix, I put the fix of issue #262 in a separate PR.

I have adapted the test suite but could not run it as I get a 

    Traceback (most recent call last):
      File "...\JetBrains\PyCharm 3.4\helpers\pycharm\utrunner.py", line 128, in <module>
        all.addTests(testLoader.loadTestsFromTestCase(getattr(module, a[1])))
      File "...\xlwings-dev\lib\unittest\loader.py", line 56, in loadTestsFromTestCase
        loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))
    TypeError: this constructor takes no arguments

Any hint on how to run the test suite ?

### CODE REVIEW

**Comment by fzumstein** [comment]
Great thanks, I should really write a developer's guide... you need to run it with nose: `nosetests`

**Comment by sdementen** [comment]
Got it and it runs without errors

**Comment by fzumstein** [comment]
I needed to fix the test, can you please check: bb0eead65f1498cfb8f967975cabcffa56256114

**Comment by sdementen** [comment]
your fix of the test is correct. I must have forgotten to run nosetests...

**Pull request merged**
