### PR TITLE
allow to read large ranges of values (above 4Mio elements)

### PR DESCRIPTION
**Pull request by sdementen**
if the range is above  4Mio elements, the range.Value raises an exception 'Not enough storage is available to complete this operation.'
To go beyond 4mio, we read the data in batches of max 4mio and aggregate the results.

We return lists when range has more than one cell (instead of tuples) as pandas.DataFrame need lists (and not tuples) in their data arg of constructor (useful if we want to be able to skip any "cleaning data" step afterwards in the pipe)

### CODE REVIEW

**Comment by fzumstein** [comment]
My first thoughts:

* It should be platform-independent
* I think that the issues is largely memory-dependent, so it shouldn't be a constant but an option: `Range(...).options(chunksize=None).value`

(for both points, see #77)

* I think the list conversion should be part of a (alternative) pipeline stage, but that's Eric's call

**Comment by sdementen** [comment]
I agree with all your points. So better move the chunking in the converter logic. The chunsize can be a general option for some converters but it is probably better expressed as number of elements (vs number of rows... at least it is what I  observed)  
Eric, some hints/directions on how to proceed ?

**Comment by fzumstein** [comment]
I still prefer chunksize=number of rows, because then it'll work the same as e.g. with [pandas.read_csv](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) and just generally I think it's more intuitive.

**Comment by sdementen** [comment]
Felix, Eric, any evolution on this topic since the time of the issue ?

**Comment by fzumstein** [comment]
shouldn't be a big deal, really ;) I'll add it to v0.10.1...

**Pull request closed without merging**
