### PR TITLE
Expand environmental vars

### PR DESCRIPTION
**Pull request by y2kbugger**
Expand the variables in the xlwings.bas config paths.
Use python for PYTHONPATH and UDF_PATH, use the windows shell for the logfile on windows.

This also fixes the slashes in some paths as well, with seeming no bad effects.

Has only been tested on windows and python 2.7.11

### CODE REVIEW

**Comment by fzumstein** [comment]
Can you quickly describe what the issues are that this PR solves?

**Comment by y2kbugger** [comment]
When deploying, it is helpful that paths can contain environmental variables.
Before, we had to do this, different for each computer:
```
    UDF_PATH = "C:\Users\karlsmith\data_tools/xlwings/ldcUDFs.py"
    LOG_FILE = "C:\Users\karlsmith\data_tools/xlwings/xlwings.log"
```
Now paths can be expanded:
```
    UDF_PATH = "%USERPROFILE%/data_tools/xlwings/ldcUDFs.py"
    LOG_FILE = "%USERPROFILE%/data_tools/xlwings/xlwings.log"
```

**Comment by y2kbugger** [comment]
Also:

> ' For cross-platform compatibility, use backslashes in relative directories

did you mean:

>' For cross-platform compatibility, use _forward_ slashes (/) in relative directories

**Comment by fzumstein** [comment]
Isn't it easier to just use `Environ("USERPROFILE")` on the side of VBA?

The backslash was by intention because of [this](https://github.com/ZoomerAnalytics/xlwings/blob/master/xlwings/xlwings.bas#L349), but you're right, Windows can cope with forward slashes so it should actually not matter which one you use at all.

**Comment by y2kbugger** [comment]
`Environ("USERPROFILE")` would solve my specific individual issue, but I wanted to give back a solution that followed the "rule of least astonishment". It actually took while to realize that the environmental variables were not getting interpreted. This was in part because that issue was confounded by another bug that I forgot to mention:

In the `PYTHONPATH` variable if you are using `"\"`, you need to escape it like this: `"\\"`. This only applied to `PYTHONPATH` the others were working with single `"\"`. This is fixed this using `os.path.normcase()`. Also, `os.path.normcase()` is required because `os.path.expandvars()` returns single `"\"` which is why I forgot to mention this bug.

**Comment by fzumstein** [comment]
OK fair enough - good catch with the PYTHONPATH!

**Comment by y2kbugger** [comment]
I didn't make any changes to `ExecuteMac/ExecuteMac2011` regarding the
environmental variable because I have no way to test that but I imagine
that someone might want use similar variables on OSX.

**Comment by fzumstein** [comment]
true and that's probably also a good argument agains `Environ()` as they don't work on Mac...

**Pull request merged**
