### PR TITLE
Use logger library over print(..)

### PR DESCRIPTION
**Pull request by njwhite**
It's easier to configure what messages are visible and where they go.

### CODE REVIEW

**Comment by fzumstein** [comment]
How are you using this? The advantage of using `print` is that you can simply change the interpreter from `pythonw` to `python` and you get the messages in the console that pops up.

**Comment by Colin-b** [comment]
The advantage of using logger is that your clients can decide where to redirect/save logs, filter them, change the formatting, etc....

Logging module provide everything print function provides, but print only provide a small subset of what logging provides.

**Comment by fzumstein** [comment]
How do you configure the logging handler when `debug=False`?

**Comment by Colin-b** [comment]
Via the python file called by xlwings. This one is setting the configuration

**Comment by fzumstein** [comment]
yeah, it does work e.g. for file based logging, but I don't manage to get it to the console when using `python` as the interpreter. And I would like to keep that.

**Comment by Colin-b** [comment]
Using a StreamHandler allows you to output to stdout. Is your question related to setting it as the default handler for xlwings users ?

**Comment by fzumstein** [comment]
No, my question is how to get it to show in the command prompt that pops up with `python` as interpreter. `logging.basicConfig(level=logging.DEBUG)` works when in debug mode but not otherwise.

**Comment by fzumstein** [comment]
replaced by #943

**Pull request closed without merging**
