### PR TITLE
Implement easy Range <-> dataframe and array conversion #255

### PR DESCRIPTION
**Pull request by sdementen**
Here is a first attempt at accessors. It is unfinished work but I'll be glad to get some feedback on it.
(I have also fixed the resize issue mentionned in issue #262

### CODE REVIEW

**Comment by fzumstein** [comment]
Ideally, the fix for #262 would be submitted in a separate PR, just because the other parts of this PR might take much longer to merge than this simple bug fix. Also, the unit tests should be extended to cover this edge case when either row_size or column_size is None.

**Comment by sdementen** [comment]
I have fix some bugs to pass all tests and remove the fix on issue #262 from this PR.
Still need some doc + extra test for extra functionnality

**Comment by sdementen** [comment]
Hello Felix, could you have a look at this PR ? It is now in more usable form. 
I would need to add a test for a multi-header and multi-index dataframe to confirm it works also for this case.

**Comment by fzumstein** [comment]
sure but you might need to wait a few more days until I find enough time to properly do it. One thing I don't like is the syntax of `as_array` because of [this](http://docs.scipy.org/doc/numpy/reference/generated/numpy.asarray.html). So maybe just `array` and `dataframe` or `df`will be better.

**Comment by sdementen** [comment]
No problem. For the syntax, no strong opinion. I wrote as_xxx because for
list it would have given .as_list instead of just .list that looked weird.
But at the end, the as_list equivalent is the default for Range.value so
not a real problem. I'll change to array and dataframe (maybe more
readable/obvious than df when rereading code)

**Comment by sdementen** [comment]
I wonder if the API could not be simplified to 

    rng.as_array = an array
    rng.as_df = a dataframe

with arguments regarding both passed as attribute of the range (in fact, what is done today).  In this way, as_array and as_df would be just properties of the Range. I would rather keep the as_ (or just as) prefix to avoid using array as a method name (as it is also the array constructor) and I do not see immediately the issue with the asarray method from numpy. It would be similar to the tolist used in pandas but bidirectional (tolist only converts to list not vice versa)

**Comment by sdementen** [comment]
This PR is superseeded by the PR #279 that has been for which I pull from your master. I close it

**Pull request closed without merging**
