### PR TITLE
Eupraxis dev issue 540 fix

### PR DESCRIPTION
**Pull request by Eupraxis**
Book() calls Books.open(), so I delegated exception handling to Books.open(). This will coordinate the exceptions thrown by Book("C:\path_to_file\bad file.xlsx") and app.books.open("C:\path_to_file\bad file.xlsx")

### CODE REVIEW

**Comment by fzumstein** [comment]
Can you remove `.project` and `.pydevproject` from your PR? you've added them to gitignore but probably only after committing...

**Comment by Eupraxis** [comment]
Ok, they're out.

**Comment by Eupraxis** [comment]
apologies for the two usernames. I had a numeric ID set for my user.name and email when I set up the local repo. It's fixed now and should link to my account.

**Comment by fzumstein** [comment]
oh one thing: can you change your destination branch to develop please?

**Comment by Eupraxis** [comment]
Sorry if this is a newb question: where do I change the target branch? Do I just create a new pull request targeted at dev?

**Comment by fzumstein** [comment]
https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Pull request merged**
