### PR TITLE
Embedding AddComment function

### PR DESCRIPTION
**Pull request by alekz112**

### CODE REVIEW

**Comment by fzumstein** [comment]
Thanks for that. However, it should be extended so that comments can also be read back again. Excel VBA has a bit of a weird object model there so we might want to think about how to implement that in xlwings.

**Comment by alekz112** [comment]
I just don't need to read comments at the moment, so I did not think about it. Good point though, I added that feature, so now you can read comment as well by Range("someRange").comment().

**Comment by fzumstein** [comment]
I guess I would implement it as property, but thing is, we then also need to add a possibility to delete it again ;) it's similar to the Range.name functionality...

**Comment by alekz112** [comment]
I see what you mean, I've rewritten it a bit, please, have a look :)

**Comment by fzumstein** [comment]
I think we'll need to be closer to the original object model (https://msdn.microsoft.com/en-us/library/office/ff196533.aspx), i.e. make the property return an obect.

**Comment by fzumstein** [comment]
Also, can you please use more specific commit messages than just "Update file x". thanks.

**Comment by fzumstein** [comment]
this is pre 0.9 refactor so has to be rewritten - see #896

**Pull request closed without merging**
