### PR TITLE
access application object from Sheet or Range (issue #253)

### PR DESCRIPTION
**Pull request by sdementen**
still need to update documentation but could not find location of doc string for xl_app and xl_workbook (that are also initialised in the __init__)

### CODE REVIEW

**Comment by sdementen** [comment]
For sake of consistency, maybe better to rename .wkb in .workbook (as in xl_workbook)

**Comment by fzumstein** [comment]
I agree on calling it `workbook`. However - this PR suffers from the same bug as issue #236. #277 might be resolving this though - so basically this has to wait until after #277 has been implemented.

**Comment by sdementen** [comment]
ok, let us wait.
for the application object, would this then be self.application (instead of self.app) ?

**Comment by fzumstein** [comment]
I guess that would make sense, yes

**Comment by sdementen** [comment]
Would making these attributes properties that would build the App or Wkb object

**Comment by sdementen** [comment]
Would making the attributes properties that build the object on the fly (by using the Excel COM objects) solve the issue ?

**Comment by fzumstein** [comment]
Don't know, but #277 is at the core of the issue, so I think it should be solved there.

**Pull request closed without merging**
