### PR TITLE
Refactor and simplify reading/writing arrays and dataframes with xlwings

### PR DESCRIPTION
**Pull request by sdementen**
Here is a draft for an evolution of the accessor concepts allowing to define formats as in

        # register a format for a DataFrameAccessor where header and index are defined and with the flag autotable (apply .table before reading data)
        register_format("my format",
                        DataFrameAccessor(header=2, index=3, autotable=True))

        Range('A1').format("my format").value = df_multiheader_multiindex
        # equivalent to
        # Range('A1').dataframe(header=2, index=3).value = df_multiheader_multiindex

        df = Range('A1').format("my format").value
        # equivalent to
        # df = Range('A1').table.dataframe(header=2, index=3).value

        assert_frame_equal(df_multiheader_multiindex, df)

It is also possible to define pre/post transformation as in

        # register a format for a DataFrameAccessor where resulting dataframe is transposed before being returned
        register_format("my format",
                        DataFrameAccessor(header=2, index=3, 
                                          on_result_read=lambda df:df.transpose(), 
                                          on_result_write=lambda df:df.transpose()))

        df = Range('A1').format("my format").value
        # equivalent to
        # df = Range('A1').table.dataframe(header=2, index=3).value.transpose()

When writing GUIs in Excel, it is really handful to define the different formats for the different data (input or output) in an Excel workbook and the just do a Range("A1").format("consumption format").value to get back a dataframe properly formatted/postprocessed (and the same when writing back data to the GUI.

### CODE REVIEW

**Comment by sdementen** [comment]
Not yet mergeable as missing docs + some extra tests, but would like to get some feedback first.

**Comment by sdementen** [comment]
I have merged the branch with the master head repo.

**Comment by sdementen** [comment]
All tests run successfully on 2.6, 2.7 and 3.4.

**Comment by fzumstein** [comment]
replaced by #381

**Pull request closed without merging**
